### ISSUE TITLE
Unable to use Given, When, Then from TechTalk.SpecFlow.Steps in BeforeScenario, AfterScenario methods

### ISSUE THREAD

**Issue by jimmymaldonadorojas** [GHPReporter/Ghpr.SpecFlow#17]
I have a class Test that inherits from TechTalk.SpecFlow.Steps, and I want to call a step definition from a BeforeScenario method without creating an instance of the Test class (to re-use code and keep the output logs)
`
public class Test : Steps{

        [Given(@"I have number (.*)")]
        public void GivenIHaveNumber(int p0)
        {
            Console.WriteLine("I have the number" + p0);
         }
        
        [BeforeScenario]
        public void BeforeScenario()
        {
            Given(string.Format("I have number {0}", 10));
        }
}
`

After executing a scenario with a similar configuration like this, I have the following error:

Test Name:	AbsoluteValueNegative
Test FullName:	Ghpr.SpecFlow.Examples.Features.MathFeatures.OtherFeature.AbsoluteValueNegative
Test Source:	D:\GHPReport\Ghpr.SpecFlow.Examples\Ghpr.SpecFlow.Examples\Ghpr.SpecFlow.Examples\Features\MathFeatures\Other.feature : line 13
Test Outcome:	Failed
Test Duration:	0:00:00.003

Result StackTrace:	
at GhprSpecFlow.Common.GhprTestRunner.Given(String text, String multilineTextArg, Table tableArg, String keyword)
   at TechTalk.SpecFlow.Steps.Given(String step)
   at Ghpr.SpecFlow.Examples.Steps.BasicsSteps.BeforeScenario() in D:\GHPReport\Ghpr.SpecFlow.Examples\Ghpr.SpecFlow.Examples\Ghpr.SpecFlow.Examples\Steps\BasicsSteps.cs:line 91
   at lambda_method(Closure , IContextManager )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.InvokeHook(IBindingInvoker invoker, IHookBinding hookBinding, HookType hookType)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioStart(ScenarioInfo scenarioInfo)
   at GhprSpecFlow.Common.GhprTestExecutionEngine.OnScenarioStart(ScenarioInfo scenarioInfo)
   at TechTalk.SpecFlow.TestRunner.OnScenarioStart(ScenarioInfo scenarioInfo)
   at GhprSpecFlow.Common.GhprTestRunner.OnScenarioStart(ScenarioInfo scenarioInfo)
   at Ghpr.SpecFlow.Examples.Features.MathFeatures.OtherFeature.ScenarioSetup(ScenarioInfo scenarioInfo)
   at Ghpr.SpecFlow.Examples.Features.MathFeatures.OtherFeature.AbsoluteValueNegative() in D:\GHPReport\Ghpr.SpecFlow.Examples\Ghpr.SpecFlow.Examples\Ghpr.SpecFlow.Examples\Features\MathFeatures\Other.feature:line 13
--TearDown
   at GhprSpecFlow.Common.GhprTestRunner.OnScenarioEnd()
   at Ghpr.SpecFlow.Examples.Features.MathFeatures.OtherFeature.ScenarioTearDown()

Result Message:	
System.NullReferenceException : Object reference not set to an instance of an object.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
Result StandardOutput:	
-> warning: The previous ScenarioContext was not disposed.
Give I have number 10
-> done: BasicsSteps.GivenIHaveNumber(10) (0.0s)

**Comment by jimmymaldonadorojas** [comment]
I was using version 0.5.0.2 for both these plugins Ghpr.Core, Ghpr.SpecFlowPlugin, and my tests work just fine, but for all the higher versions (adding Ghpr.SpecFlow.Common) I have the error

Note: I am using the latest versions of Specflow and NUnit as well.

**Comment by elv1s42** [comment]
Hi @jimmymaldonadorojas !

Thank you for this issue, I'll try to reproduce and fix it.

**Comment by elv1s42** [comment]
Should be working now

**Comment by jimmymaldonadorojas** [comment]
Thanks, I will test it
